.TH "booking_system/main.cpp" 3 "Version v1.0" "Booking System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
booking_system/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'ararat_teather\&.h'\fP
.br
\fR#include 'yerevan_teather\&.h'\fP
.br
\fR#include 'nairi_teather\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_teather_list\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Sergey Brutyan sbrutyan01@gmail.com 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0
.RE
.PP
.SH "DESCRITPION"
.PP
This class represents the main and all is functionalities 
.SH "Function Documentation"
.PP 
.SS "int main ()"
three teathers as objects

.PP
set movie names list

.PP
set movie names list

.PP
set movie names list

.PP
command that entered by user

.PP
seat name variable enterd by user

.PP
select teather Ararat Teather

.PP
select movie #1 in ararat teather

.PP
seat booking procedure for ararat teather for movie #1

.PP
exit from seat booking procedure for ararat teather for movie #1

.PP
select movie #2 in ararat teather

.PP
seat booking procedure for ararat teather for movie #2

.PP
exit from seat booking procedure for ararat teather for movie #2

.PP
select movie #3 in ararat teather

.PP
seat booking procedure for ararat teather for movie #3

.PP
exit from seat booking procedure for ararat teather movie #3

.PP
exit from movie selection menu in ararat teather

.PP
exit from ararat teather menu

.PP
ararat teather selection finished here

.PP
select teather Yerevan Teather

.PP
show movie list in yerevan teather

.PP
yerevan teather movie selection menu

.PP
select movie #1 in yerevan teather

.PP
seat booking procedure for yerevan teather for movie #1

.PP
exit from seat booking procedure for yerevan teather movie #1

.PP
select movie #2 in yerevan teather

.PP
seat booking procedure in yerevan teather for movie #2

.PP
exit from program after booking seat

.PP
select yerevan teather movie #3

.PP
seats bookiing procedure for yerevan teather for movie #3

.PP
exit from seat booking procedure for yerevan teather for movie #3

.PP
exit from movie selection menu in yerevan teather

.PP
exit from yerevan teather menu

.PP
yerevan teather selection is finished here

.PP
select Nairi Teather

.PP
show movie list in Nairi teather 
.br

.PP
nairi teather movie selection menu

.PP
nairi teather movie #1 selection

.PP
seat booking procedure in nairi teather for movie #1

.PP
exit seat booking procedure for nairi teather for movie #1

.PP
nairi teather movie #2 selection

.PP
seats booking procedure in nairi teather for movie #2

.PP
exit procedure for nairi teather for movie #2

.PP
nairi teather movie #3 selection

.PP
seat booking procedure in nairi teather for movie #3

.PP
exit from seat booking procedure in nairi teather for movie #3

.PP
exit from nairi teather from movie selection list menu

.PP
exit from nairi teather menu

.PP
nairi teather selection is finished here

.PP
exit from teather selection list

.PP
exit from teather selection list

.PP
exit from teather selection list

.PP
exit from booking system (global menu)

.PP
forever loop for menu and selections

.PP
destructor for ararat teather object

.PP
destructor for yerevan teather object

.PP
destructor for nairi teather object
.SS "void print_teather_list ()"
global function prototype to only show teather list

.PP
global function for only showing teather list 
.SH "Author"
.PP 
Generated automatically by Doxygen for Booking System from the source code\&.
