.TH "booking_system/nairi_teather.h" 3 "Version v1.0" "Booking System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
booking_system/nairi_teather.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <map>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnairi_teather\fP"
.br
.RI "Nairi Teather class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNAIRI_TEATHER_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Sergey Brutyan sbrutyan01@gmail.com 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0
.RE
.PP
.SH "DESCRITPION"
.PP
This class represents the Nairi Teather and all is functionalities 
.SH "Macro Definition Documentation"
.PP 
.SS "#define NAIRI_TEATHER_H"
headers from standard library 
.SH "Author"
.PP 
Generated automatically by Doxygen for Booking System from the source code\&.
